export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";

export const ORDER_DETAILS_REQUEST = "ORDERS_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDERS_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDERS_DETAILS_FAIL";
