export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";

export const ORDER_DETAILS_REQUEST = "ORDERS_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDERS_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDERS_DETAILS_FAIL";

export const ORDER_PAY_REQUEST = "ORDERS_PAY_REQUEST";
export const ORDER_PAY_SUCCESS = "ORDERS_PAY_SUCCESS";
export const ORDER_PAY_FAIL = "ORDERS_PAY_FAIL";
export const ORDER_PAY_RESET = "ORDERS_PAY_RESET";
